//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participation()
        {
            this.Drink = new HashSet<Drink>();
        }
    
        public int MemberId { get; set; }
        public int EventId { get; set; }
        public Nullable<double> Credit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drink> Drink { get; set; }
        public virtual Event Event { get; set; }
        public virtual Member Member { get; set; }
    }
}
